name: Sync Tailscale ACLs
on:
  push:
    branches: [main]
    paths: [policy.hujson]
  pull_request:
    branches: [main]
    paths: [policy.hujson]

jobs:
  sync-acls:
    runs-on: arc-runner-set
    steps:
      - uses: actions/checkout@v4
      - uses: tailscale/gitops-acl-action@v1
        with:
          api-key: ${{ env.TS_API_KEY }}
          tailnet: amerenda.github
